---
platform: linux

resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

- name: ftp
  type: docker-image
  source:
    repository: aequitas/ftp-resource

resources:
- name: concourse-pipeline
  type: concourse-pipeline
  source:
    target: ((concourse_url))
    teams:
    - name: ((concourse_team))
      username: ((concourse_username))
      password: ((concourse_password))

- name: ci-config
  type: git
  source:
    branch: master
    uri: ((git_pipeline_url))
    private_key: ((git_key))
    git_crypt_key: ((git_crypt_key))

- name: src
  type: git
  source:
    uri: ((git_url))
    branch: master
    private_key: ((git_key))

- name: src-workspace
  type: git
  source:
    uri: ((git_url))
    branch: workspace
    private_key: ((git_key))

# - name: gh-release
#   type: github-release
#   source:
#     owner: shokinn
#     repository: emby-updater
#     access_token: ((git_access_token))

- name: artifact-store
  type: ftp
  source:
    regex: (?P<file>emby-updater-(?P<version>[0-9\.]+))
    uri: ftp://((ftp_user)):((ftp_password))@((ftp_uri))/artifacts/emby-updater/


#############################
# JOBS
#############################
jobs:

#############################
# Update Pipeline
#############################
- name: update-pipeline
  plan:
  - get: ci-config
    trigger: true
  - put: concourse-pipeline
    params:
      pipelines:
      - name: ((concourse_pipeline))
        team: ((concourse_team))
        config_file: ci-config/pipeline.yml
        vars_files:
        - ci-config/credentials.yml

#############################
### Build workspace
#############################
- name: build-workspace
  plan:
  - get: src-workspace
    trigger: true
  - task: build_workspace
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: shokinn/emby-updater-buildimg
          tag: latest
      inputs:
        - name: src-workspace
      run:
        path: sh
        args:
        - -exc
        - |
          cd ./src-workspace
          /root/.local/bin/pyinstaller --onefile emby-updater.py
          cd ./dist
          ./emby-updater --version

#############################
### Build releae
#############################
- name: build
  plan:
  - get: src
    trigger: true
  - task: build_emby-updater
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: shokinn/emby-updater-buildimg
          tag: latest
      inputs:
        - name: src
      outputs:
        - name: artifact-store
      run:
        path: sh
        args:
        - -exc
        - |
          cd ./src
          /root/.local/bin/pyinstaller --onefile emby-updater.py
          cd ../artifact-store
          cp ../src/dist/emby-updater ./emby-updater-$(../src/dist/emby-updater --version | cut -d ' ' -f2)
  - put: artifact-store
    params:
      file: "artifact-store/*"